/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WizardRouteImport } from './routes/wizard'
import { Route as SparesRouteImport } from './routes/spares'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as KnowledgeRouteImport } from './routes/knowledge'
import { Route as EquipmentRouteImport } from './routes/equipment'
import { Route as AlertsRouteImport } from './routes/alerts'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EquipmentIdRouteImport } from './routes/equipment.$id'
import { Route as ApiWizardRouteImport } from './routes/api/wizard'

const WizardRoute = WizardRouteImport.update({
  id: '/wizard',
  path: '/wizard',
  getParentRoute: () => rootRouteImport,
} as any)
const SparesRoute = SparesRouteImport.update({
  id: '/spares',
  path: '/spares',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const KnowledgeRoute = KnowledgeRouteImport.update({
  id: '/knowledge',
  path: '/knowledge',
  getParentRoute: () => rootRouteImport,
} as any)
const EquipmentRoute = EquipmentRouteImport.update({
  id: '/equipment',
  path: '/equipment',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertsRoute = AlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EquipmentIdRoute = EquipmentIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => EquipmentRoute,
} as any)
const ApiWizardRoute = ApiWizardRouteImport.update({
  id: '/api/wizard',
  path: '/api/wizard',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/equipment': typeof EquipmentRouteWithChildren
  '/knowledge': typeof KnowledgeRoute
  '/reports': typeof ReportsRoute
  '/spares': typeof SparesRoute
  '/wizard': typeof WizardRoute
  '/api/wizard': typeof ApiWizardRoute
  '/equipment/$id': typeof EquipmentIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/equipment': typeof EquipmentRouteWithChildren
  '/knowledge': typeof KnowledgeRoute
  '/reports': typeof ReportsRoute
  '/spares': typeof SparesRoute
  '/wizard': typeof WizardRoute
  '/api/wizard': typeof ApiWizardRoute
  '/equipment/$id': typeof EquipmentIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/equipment': typeof EquipmentRouteWithChildren
  '/knowledge': typeof KnowledgeRoute
  '/reports': typeof ReportsRoute
  '/spares': typeof SparesRoute
  '/wizard': typeof WizardRoute
  '/api/wizard': typeof ApiWizardRoute
  '/equipment/$id': typeof EquipmentIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/alerts'
    | '/equipment'
    | '/knowledge'
    | '/reports'
    | '/spares'
    | '/wizard'
    | '/api/wizard'
    | '/equipment/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/alerts'
    | '/equipment'
    | '/knowledge'
    | '/reports'
    | '/spares'
    | '/wizard'
    | '/api/wizard'
    | '/equipment/$id'
  id:
    | '__root__'
    | '/'
    | '/alerts'
    | '/equipment'
    | '/knowledge'
    | '/reports'
    | '/spares'
    | '/wizard'
    | '/api/wizard'
    | '/equipment/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlertsRoute: typeof AlertsRoute
  EquipmentRoute: typeof EquipmentRouteWithChildren
  KnowledgeRoute: typeof KnowledgeRoute
  ReportsRoute: typeof ReportsRoute
  SparesRoute: typeof SparesRoute
  WizardRoute: typeof WizardRoute
  ApiWizardRoute: typeof ApiWizardRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wizard': {
      id: '/wizard'
      path: '/wizard'
      fullPath: '/wizard'
      preLoaderRoute: typeof WizardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spares': {
      id: '/spares'
      path: '/spares'
      fullPath: '/spares'
      preLoaderRoute: typeof SparesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/knowledge': {
      id: '/knowledge'
      path: '/knowledge'
      fullPath: '/knowledge'
      preLoaderRoute: typeof KnowledgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipment': {
      id: '/equipment'
      path: '/equipment'
      fullPath: '/equipment'
      preLoaderRoute: typeof EquipmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerts': {
      id: '/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipment/$id': {
      id: '/equipment/$id'
      path: '/$id'
      fullPath: '/equipment/$id'
      preLoaderRoute: typeof EquipmentIdRouteImport
      parentRoute: typeof EquipmentRoute
    }
    '/api/wizard': {
      id: '/api/wizard'
      path: '/api/wizard'
      fullPath: '/api/wizard'
      preLoaderRoute: typeof ApiWizardRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface EquipmentRouteChildren {
  EquipmentIdRoute: typeof EquipmentIdRoute
}

const EquipmentRouteChildren: EquipmentRouteChildren = {
  EquipmentIdRoute: EquipmentIdRoute,
}

const EquipmentRouteWithChildren = EquipmentRoute._addFileChildren(
  EquipmentRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlertsRoute: AlertsRoute,
  EquipmentRoute: EquipmentRouteWithChildren,
  KnowledgeRoute: KnowledgeRoute,
  ReportsRoute: ReportsRoute,
  SparesRoute: SparesRoute,
  WizardRoute: WizardRoute,
  ApiWizardRoute: ApiWizardRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
